<?php
session_start();
require "../config.php";
require "../dao/ProductoDao.php";
require "../dao/GrupoCategoriaDao.php";
require "../utils/Tools.php";

$grupoCategoriaDao = new GrupoCategoriaDao();
$conexion = (new Conexion())->getConexion();
$productoDao = new ProductoDao();
$tools = new Tools();

$dataConf = $tools->getConfiguracion();
$listaRamByCat = $productoDao->getDataRandonE();

$listaGrupos = $grupoCategoriaDao->getListaCate();
$listProdBan = $productoDao->getRandomInfo(1);
$palabra = "";
if (isset($_GET['search'])) {
    $palabra = $_GET['search'];
}

$tipoPrecios = [
    'vp' => 'Precios VIP',
    'dt' => 'Precios DISTRIBUCI&Oacute;N'
];

$vh1 = isset($_GET['v']) && isset($tipoPrecios[$_GET['v']])
    ? $tipoPrecios[$_GET['v']]
    : '';

$vripo = $_GET['v'] ?? '';

$sql = "SELECT cod_sub1 as codi_categoria, nom_sub1 as nombre FROM sopsub1 WHERE cod_sub1 != '000' ORDER BY cod_sub1";
$listaGrupos = $conexion->query($sql);
?><!DOCTYPE html>
<?php include '../fragment/head_general.php' ?>
<!-- SITE TITLE -->
<title>COMPUTER</title>
<!-- Favicon Icon -->
<link rel="shortcut icon" type="image/x-icon" href="../public/favi.png">
<!-- Animation CSS -->
<link rel="stylesheet" href="../public/assets/css/animate.css">
<!-- Latest Bootstrap min CSS -->
<link rel="stylesheet" href="../public/assets/bootstrap/css/bootstrap.min.css">
<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800,900&display=swap"
    rel="stylesheet">
<!-- Icon Font CSS -->
<link rel="stylesheet" href="../public/assets/css/all.min.css">
<link rel="stylesheet" href="../public/assets/css/ionicons.min.css">
<link rel="stylesheet" href="../public/assets/css/themify-icons.css">
<link rel="stylesheet" href="../public/assets/css/linearicons.css">
<link rel="stylesheet" href="../public/assets/css/flaticon.css">
<link rel="stylesheet" href="../public/assets/css/simple-line-icons.css">
<!--- owl carousel CSS-->
<link rel="stylesheet" href="../public/assets/owlcarousel/css/owl.carousel.min.css">
<link rel="stylesheet" href="../public/assets/owlcarousel/css/owl.theme.css">
<link rel="stylesheet" href="../public/assets/owlcarousel/css/owl.theme.default.min.css">
<!-- Magnific Popup CSS -->
<link rel="stylesheet" href="../public/assets/css/magnific-popup.css">
<!-- jquery-ui CSS -->
<link rel="stylesheet" href="../public/assets/css/jquery-ui.css">
<!-- Slick CSS -->
<link rel="stylesheet" href="../public/assets/css/slick.css">
<link rel="stylesheet" href="../public/assets/css/slick-theme.css">
<!-- Style CSS -->
<link rel="stylesheet" href="../public/assets/css/style.css">
<link rel="stylesheet" href="../public/assets/css/responsive.css">
<link rel="stylesheet" href="../public/plugin/sweetalert2/sweetalert2.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<style>
    .float {
        padding-top: 7px;
        position: fixed;
        width: 60px;
        height: 60px;
        bottom: 40px;
        right: 80px;
        background-color: #25d366;
        color: #FFF;
        border-radius: 50px;
        text-align: center;
        font-size: 30px;
        box-shadow: 2px 2px 3px #999;
        z-index: 100;
    }
</style>
<style type="text/css">
    #loader-pre-prod {
        display: block;
        position: absolute;
        z-index: 500;
        background-color: #ffffffb8;
        width: 100%;
        height: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    @keyframes ldio-tsbmxkn5l7n {
        0% {
            transform: translate(-50%, -50%) rotate(0deg);
        }

        100% {
            transform: translate(-50%, -50%) rotate(360deg);
        }
    }

    .ldio-tsbmxkn5l7n div {
        position: absolute;
        width: 120px;
        height: 120px;
        border: 20px solid #ff3d57;
        border-top-color: transparent;
        border-radius: 50%;
    }

    .ldio-tsbmxkn5l7n div {
        animation: ldio-tsbmxkn5l7n 1s linear infinite;
        top: 100px;
        left: 100px
    }

    .loadingio-spinner-rolling-ox3sfpgdu8h {
        width: 200px;
        height: 200px;
        display: inline-block;
        overflow: hidden;
        background: none;
    }

    .ldio-tsbmxkn5l7n {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(1);
        backface-visibility: hidden;
        transform-origin: 0 0;
        /* see note above */
    }

    .ldio-tsbmxkn5l7n div {
        box-sizing: content-box;
    }

    /* generated by https://loading.io/ */
</style>
<style>
    .on-click-cont:hover {
        cursor: pointer;
    }
    .product_img {
        height: 220px;
        overflow: hidden;
        display: flex;
        align-items: center;
        justify-content: center;
        background: #f9f9f9;
    }
    .product_img img {
        width: 100%;
        height: 100%;
        object-fit: contain;
    }
</style>
</head>

<body>

    <!-- LOADER -->
    <div class="preloader">
        <div class="lds-ellipsis">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
    <!-- END LOADER -->

    <!-- End Screen Load Popup Section -->

    <!-- START HEADER -->
    <?php include "../fragment/head_secon.php"; ?>
    <!-- END HEADER -->

    <!-- START SECTION BREADCRUMB -->
    <div class="breadcrumb_section bg_gray page-title-mini" style="padding-bottom: 20px;padding-top: 20px;">
        <div class="container"><!-- STRART CONTAINER -->
            <div class="row align-items-center">
                <div class="col-md-6">
                    <div class="page-title">
                        <h1>Productos <?= $vh1 ?></h1>
                    </div>
                </div>
                <div class="col-md-6">
                    <ol class="breadcrumb justify-content-md-end">
                        <li hidden class="breadcrumb-item"><a href="#">Inicio</a></li>
                        <li hidden class="breadcrumb-item"><a href="#">Pagina</a></li>
                        <li style="font-size: 18px;color: #232323">TC: <span style="color: white">-</span>
                            <strong><?= $tc ?></strong>
                        </li>
                    </ol>
                </div>
            </div>
        </div><!-- END CONTAINER-->
    </div>
    <!-- END SECTION BREADCRUMB -->

    <!-- START MAIN CONTENT -->
    <div class="main_content">

        <!-- START SECTION SHOP -->
        <div class="section" style="padding-top: 29px;">

            <input value="<?= $palabra ?>" id="palabra" type="hidden">

            <div class="custom-container" id="app_shop">
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-9">
                        <form action="shop-list-prod.php" method="GET"
                            style="padding-bottom: 20px;display: block;margin: auto;" class="col-md-12">
                            <input value="<?= $vripo ?>" name="v" id="flista" type="hidden">
                            <div class="search-container">
                                <input class="rounded-left-input" name="search" placeholder="Buscar producto"
                                    required="" type="text">
                                <button type="submit" class="search-btn"><i class="fa fa-search"></i></button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-9" id="content_principal">
                        <div class="row mb-4">
                            <div class="col-md-4"></div>
                            <div class="col-md-4">
                                <div class="custom_select">
                                    <select class="form-control form-control-sm" @change="changePrecio($event)">
                                        <option value="">--</option>
                                        <option value="asc">Precio: del m&aacute;s bajo al m&aacute;s alto</option>
                                        <option value="desc">Precio: del m&aacute;s alto al m&aacute;s bajo</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4"></div>
                        </div>


                        <div class="row shop_container grid">
                            <div id="loader-pre-prod">

                                <div class="loadingio-spinner-rolling-ox3sfpgdu8h">
                                    <div class="ldio-tsbmxkn5l7n">
                                        <div></div>
                                    </div>
                                </div>

                            </div>
                            <div v-for="(item, index) in listaHoja" class="col-md-4 col-6 col-lg-3">
                                <div class="product">
                                    <div class="product_img">
                                        <a :href="'shop-product-detail.php?prod='+item.prod_id">
                                            <img :src="item.imagen1 ? (item.imagen1.startsWith('http') ? item.imagen1 : '<?= API_URL ?>/storage/'+item.imagen1) : ''" :alt="item.nombre">
                                        </a>
                                        <div class="product_action_box">
                                            <ul class="list_none pr_action_btn">
                                                <li class="add-to-cart"><a v-on:click="agregarCarritoProd(index)"
                                                        href="javascript:void(0);"><i class="icon-basket-loaded"></i>
                                                        Añadir al carrito</a></li>
                                                <!--<li><a href="shop-compare.html" class="popup-ajax"><i class="icon-shuffle"></i></a></li>
                                        <li><a href="shop-quick-view.html" class="popup-ajax"><i class="icon-magnifier-add"></i></a></li>-->
                                                <li><a href="#"><i class="icon-heart"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="product_info">
                                        <h6 class="product_title titulo_prod"><a
                                                :href="'shop-product-detail.php?prod='+item.prod_id">{{item.nombre}}</a>
                                        </h6>
                                        <div v-if="!item.is_ofert" class="product_price">
                                            <!--<span class="price">${{formatNumerPrecio(item.precio)}}</span>-->
                                            <span class=""><strong>S/. {{getCamBio(item.precio)}}</strong></span>
                                            <br>
                                            <br>
                                            <!--del>$88.00</del>
                                    <div class="on_sale">
                                        <span>Ahorra $20.00</span>
                                    </div-->
                                        </div>
                                        <!--<div v-if="item.is_ofert" class="product_price">
                                    <span class="price">${{formatNumerPrecio(item.precio_ofer)}}</span>
                                    <del>${{formatNumerPrecio(item.precio)}}</del>

                                </div>-->
                                        <div v-if="item.is_ofert" class="product_price">
                                            <span class="price">S/.{{getCamBio(item.precio_ofer)}}</span>
                                            <del>S/.{{getCamBio(item.precio)}}</del>

                                        </div>
                                        <div class="rating_wrap">

                                            <span class="rating_num"> <strong>Stock: <a href="javascript:void(0)">
                                                        <span v-if="formartNumberStock(item.stock)==0"
                                                            style="font-weight: lighter;color: #d70000"> Sin
                                                            Stock</span>
                                                        <span
                                                            v-if="formartNumberStock(item.stock)<=10&&formartNumberStock(item.stock)>0"
                                                            style="font-weight: lighter;color: #03ad01">
                                                            {{formartNumberStock(item.stock)}} en Stock</span>
                                                        <span v-if="formartNumberStock(item.stock)>10"
                                                            style="font-weight: lighter;color: #03ad01">+ de 10 en
                                                            Stock</span>
                                                    </a></strong></span>
                                        </div>
                                        <div class="pr_desc">
                                            <p>* {{item.content1}}</p>
                                            <p>* {{item.content2}}</p>
                                            <p>* {{item.content3}}</p>
                                        </div>
                                        <!--div class="pr_switch_wrap">
                                    <div class="product_color_switch">
                                        <span class="active" data-color="#87554B"></span>
                                        <span data-color="#333333"></span>
                                        <span data-color="#DA323F"></span>
                                    </div>
                                </div-->
                                        <div class="list_product_action_box">
                                            <ul class="list_none pr_action_btn">
                                                <li class="add-to-cart"><a v-on:click="agregarCarritoProd(index)"
                                                        href="javascript:void(0);"><i class="icon-basket-loaded"></i>
                                                        Añadir al carrito</a></li>
                                                <!--<li><a href="shop-compare.html" class="popup-ajax"><i class="icon-shuffle"></i></a></li>
                                        <li><a href="shop-quick-view.html" class="popup-ajax"><i class="icon-magnifier-add"></i></a></li>-->
                                                <li><a href="#"><i class="icon-heart"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>


                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div id="example" style="margin: auto;display: block;"></div>
                                <!--ul style="display: none" class="pagination mt-3 justify-content-center pagination_style1">
                            <li v-on:click="setSwithHoja(-1)" class="page-item"><a class="page-link" href="javascript:void(0)"><i class="linearicons-arrow-left"></i></a></li>

                            <li v-for="item  in getPagNum" :class="hojaActual==item?'page-item active':'page-item'" v-on:click="setNumHoja(item)"><a class="page-link" href="javascript:void(0)">{{item}}</a></li>

                            <li v-on:click="setSwithHoja(1)"  class="page-item"><a class="page-link"  href="javascript:void(0)"><i class="linearicons-arrow-right"></i></a></li>
                        </ul-->
                            </div>
                        </div>
                    </div>


                    <div class="col-lg-3 order-lg-first mt-4 pt-2 mt-lg-0 pt-lg-0">
                        <div class="sidebar">

                            <!-- CATEGORÍAS -->
                            <div class="widget" style="border: 1px solid #c7161d;">
                                <div style="background-color:#c7161d;overflow:auto;padding-top:4px;padding-left:6px;">
                                    <h5 class="widget_title" style="text-transform:uppercase;color:white;margin-bottom:11px;">Categorias</h5>
                                </div>
                                <ul class="widget_categories" style="padding-left:16px;padding-right:5px;max-height:220px;overflow-y:auto;">
                                    <li>
                                        <a style="font-weight:bold;cursor:pointer"
                                            :style="categoriaActiva===null?'color:#c7161d':''"
                                            @click.prevent="filtrarCategoria(null)">
                                            <span class="categories_name">Todas</span>
                                        </a>
                                    </li>
                                    <li v-for="cat in listaCategorias" :key="cat.id">
                                        <a style="font-weight:bold;cursor:pointer"
                                            :style="categoriaActiva===cat.id?'color:#c7161d':''"
                                            @click.prevent="filtrarCategoria(cat.id)">
                                            <span class="categories_name">{{cat.nombre}}</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                            <!-- FILTROS -->
                            <div class="widget">
                                <div style="border:1px solid #c7161d;">
                                    <div style="background-color:#c7161d;overflow:auto;padding-top:4px;padding-left:6px;">
                                        <h5 style="text-transform:uppercase;color:white;margin-bottom:11px;" class="widget_title">Filtrar por</h5>
                                    </div>
                                    <div style="padding:11px;">

                                        <!-- Rango de Precio -->
                                        <div class="widget">
                                            <h5 class="widget_title">Rango de Precio (S/.)</h5>
                                            <div class="price_filter">
                                                <div id="price_first" style="margin-bottom:10px;"></div>
                                                <div class="price_slider_amount" style="display:flex;justify-content:space-between;align-items:center;margin-top:8px;">
                                                    <span style="font-size:13px;">S/. <span id="slider_min">0</span> — S/. <span id="slider_max">5000</span></span>
                                                    <button onclick="APP_PROD.getFiltrar()" class="btn btn-sm" style="background:#c7161d;color:white;">
                                                        <i class="fa fa-search"></i>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>

                                        <!-- Marcas -->
                                        <div class="widget">
                                            <h5 class="widget_title">Marcas</h5>
                                            <ul class="list_brand" style="max-height:200px;overflow-y:auto;">
                                                <li v-for="marca in listaMarcasApi" :key="marca.cod_marca">
                                                    <div class="custome-checkbox">
                                                        <input class="form-check-input" type="checkbox"
                                                            :id="'marca-'+marca.cod_marca"
                                                            :value="marca.cod_marca"
                                                            v-model="marcasFiltro"
                                                            @change="onMarcaChange()">
                                                        <label class="form-check-label" :for="'marca-'+marca.cod_marca">
                                                            <span>{{marca.nombre_marca}}</span>
                                                        </label>
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>

                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END SECTION SHOP -->

        <!-- START SECTION SUBSCRIBE NEWSLETTER -->
        <?php require_once "../fragment/plantilla_suscribete.php" ?>
        <!-- START SECTION SUBSCRIBE NEWSLETTER -->

    </div>


    <!-- END MAIN CONTENT -->

    <!-- START FOOTER -->
    <?php include "../fragment/footer_gen.php" ?>
    <!-- END FOOTER -->

    <a href="#" class="scrollup" style="display: none;"><i class="ion-ios-arrow-up"></i></a>

    <!-- Latest jQuery -->
    <script src="../public/assets/js/jquery-1.12.4.min.js"></script>
    <script>
        $(".preloader").hide()
    </script>
    <!-- jquery-ui -->
    <script src="../public/assets/js/jquery-ui.js"></script>
    <!-- popper min js -->
    <script src="../public/assets/js/popper.min.js"></script>
    <!-- Latest compiled and minified Bootstrap -->
    <script src="../public/assets/bootstrap/js/bootstrap.min.js"></script>
    <!-- owl-carousel min js  -->
    <script src="../public/assets/owlcarousel/js/owl.carousel.min.js"></script>
    <!-- magnific-popup min js  -->
    <script src="../public/assets/js/magnific-popup.min.js"></script>
    <!-- waypoints min js  -->
    <script src="../public/assets/js/waypoints.min.js"></script>
    <!-- parallax js  -->
    <script src="../public/assets/js/parallax.js"></script>
    <!-- countdown js  -->
    <script src="../public/assets/js/jquery.countdown.min.js"></script>
    <!-- imagesloaded js -->
    <script src="../public/assets/js/imagesloaded.pkgd.min.js"></script>
    <!-- isotope min js -->
    <script src="../public/assets/js/isotope.min.js"></script>
    <!-- jquery.dd.min js -->
    <script src="../public/assets/js/jquery.dd.min.js"></script>
    <!-- slick js -->
    <script src="../public/assets/js/slick.min.js"></script>
    <!-- elevatezoom js -->
    <script src="../public/assets/js/jquery.elevatezoom.js"></script>
    <!-- scripts js-->
    <script src="../public/assets/js/scripts.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>
    <script src="../public/js/tools.js"></script>
    <script src="../public/js/main.js?v=8"></script>
    <script src="../public/plugin/sweetalert2/vue-swal.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="../public/js/bootstrap-paginator.js"></script>

</body>

<script type='text/javascript'>

    var options = {
        currentPage: 1,
        totalPages: 2,
        alignment: 'center',
        shouldShowPage: function (type, page, current) {
            switch (type) {
                case "first":
                case "last":
                    return false;
                default:
                    return true;
            }
        },
        onPageClicked: function (e, originalEvent, type, page) {
            APP_PROD.setNumHoja(page)

        }
    }
    var pagPaginador
    $(document).ready(function () {

        $('#example').bootstrapPaginator(options);
    })
</script>
<script>

    $("#loader-pre-prod").hide();

    var $container22;
    const APP_PROD = new Vue({
        el: "#app_shop",
        data: {
            valueUSDMin: 0,
            valueUSDMax: 5000,
            palabra: '',
            listaProdGene: [],
            listaBusquedaE: [],
            listaMarcar: [],
            listaHoja: [],
            cntPorHoja: 0,
            cntItemPorHoja: 12,
            cntHojas: 0,
            hojaActual: 1,
            cantidadProd: 0,
            lasrId: 0,
            listaMarcaFiltro: [],
            tc: 1,
            flista: '',
            listaCategorias: [],
            listaMarcasApi: [],
            categoriaActiva: null,
            marcasFiltro: [],
        },
        methods: {
            changePrecio(event) {

                this.ordenpres = event.target.value;
                this.listaHoja = [...this.listaHoja].sort((a, b) => {
                    if (this.ordenpres === 'asc') {
                        return a.precio - b.precio;
                    }
                    if (this.ordenpres === 'desc') {
                        return b.precio - a.precio;
                    }
                });

            },
            getCamBio(precio) {
                return (parseFloat(precio) * 1).toFixed(2);
            },
            establecerTC() {
                this.tc = parseFloat($("#tasa_cambio").val());
            },
            formartNumberStock(num) {
                return parseInt(num + "");
            },
            agregarFiltroMarca(mar) {
                this.listaMarcaFiltro.push(mar)
            },
            eliminarFiltroMarca(mar) {
                var index = this.listaMarcaFiltro.indexOf(mar);
                this.listaMarcaFiltro.splice(index, 1);
            },
            cargarCategorias() {
                const vue = this
                $.ajax({
                    type: "GET",
                    url: "<?= API_URL ?>/api/public/categorias",
                    success: function (resp) {
                        if (resp.success) vue.listaCategorias = resp.data
                    }
                })
            },
            cargarMarcas() {
                const vue = this
                $.ajax({
                    type: "GET",
                    url: "<?= API_URL ?>/api/public/marcas",
                    success: function (resp) {
                        if (resp.success) vue.listaMarcasApi = resp.data
                    }
                })
            },
            filtrarCategoria(id) {
                this.categoriaActiva = id
                this.hojaActual = 1
                this.paginadorListaServer()
            },
            onMarcaChange() {
                this.hojaActual = 1
                this.paginadorListaServer()
            },
            getFiltrar() {
                this.hojaActual = 1
                this.paginadorListaServer()
            },
            paginadorListaServer() {
                this.flista = $('#flista').val();
                const vue = this

                const params = new URLSearchParams({
                    per_page: this.cntItemPorHoja,
                    page: this.hojaActual,
                });
                if (APP_PROD._data.palabra) params.append('search', APP_PROD._data.palabra);
                if (this.valueUSDMin > 0) params.append('min_precio', this.valueUSDMin);
                if (this.valueUSDMax > 0 && this.valueUSDMax < 5000) params.append('max_precio', this.valueUSDMax);
                if (this.ordenpres) params.append('sort', this.ordenpres);
                if (this.categoriaActiva) params.append('categoria', this.categoriaActiva);
                if (this.marcasFiltro.length > 0) params.append('marca', this.marcasFiltro[0]);

                $("#loader-pre-prod").show();
                $(".scrollup").click()
                $.ajax({
                    type: "GET",
                    url: "<?= API_URL ?>/api/public/shop-productos?" + params.toString(),
                    success: function (resp) {
                        $("#loader-pre-prod").hide()
                        console.log(resp);
                        vue.listaHoja = resp.data
                        const totalPages = resp.pagination.last_page
                        if (options.totalPages != totalPages) {
                            options.totalPages = totalPages
                            $('#example').bootstrapPaginator(options);
                        }
                    }
                })
            },
            getDataProdListaPag2() {
                /*const cnt = this.cntItemPorHoja;
                const min = this.lasrId;
                console.log(APP_PROD._data.palabra);
                $.ajax({
                    type: "POST",
                    url: "../ajax/ajs_productos.php",
                    data: {tipo:'pag-search2',pal:APP_PROD._data.palabra,
                        forma:"<?= (isset($_GET['type']) || strlen($_GET['type']) > 0) ? $_GET['type'] : 'all' ?>",

            },
            success: function (resq) {

                resq = JSON.parse(resq);
                //console.log(resq);
                //resq = resq.reverse();
                // APP_PROD._data.listaHoja= resq
                APP_PROD._data.listaProdGene = resq
                APP_PROD._data.listaBusquedaE = resq
                APP_PROD.getPreparePagination2();
                APP_PROD.setListaMarcas();
                console.log('lista');
                $(".scrollup").click()
            }
        });*/

            },
    resetFiter(){
        this.listaBusquedaE = [];
        for (var i = 0; i < this.listaProdGene.length; i++) {
            const precioProd = parseFloat(this.listaProdGene[i].precio + "");
            if (precioProd >= this.valueUSDMin && precioProd <= this.valueUSDMax) {
                if (this.listaMarcaFiltro.length > 0) {

                    if (this.listaMarcaFiltro.indexOf(this.listaProdGene[i].marca) != -1) {
                        if (en_stock_filtro) {
                            if (parseFloat(this.listaProdGene[i].stock) > 0) {
                                this.listaBusquedaE.push(this.listaProdGene[i]);
                            }
                        } else {
                            this.listaBusquedaE.push(this.listaProdGene[i]);
                        }
                    }

                } else {
                    if (en_stock_filtro) {
                        if (parseFloat(this.listaProdGene[i].stock) > 0) {
                            this.listaBusquedaE.push(this.listaProdGene[i]);
                        }
                    } else {
                        this.listaBusquedaE.push(this.listaProdGene[i]);
                    }
                }

            }
        }
        this.getPreparePagination2();

    },
    getPreparePagination2(){
        console.log("aaaaaaaaaa")
        this.paginadorListaServer()
        /*this.cntHojas = Math.ceil(this.listaBusquedaE.length/this.cntItemPorHoja);
        options.totalPages=this.cntHojas
        $('#example').bootstrapPaginator(options);
        this.viewDataHojaSc();*/
    },
    viewDataHojaSc(){
        this.listaHoja = [];
        //this.numCntHojas = Math.ceil(this.listaProductos.length/this.itemMaximo);
        for (var i = (this.hojaActual - 1) * this.cntItemPorHoja; i < this.cntItemPorHoja * this.hojaActual; i++) {
            if (i < this.listaBusquedaE.length) {
                this.listaHoja.push(this.listaBusquedaE[i]);
            } else {
                break;
            }
        }
        // $(".scrollup").click()
    },

    agregarCarritoProd(index){
        //swal('Opción no habilitada',"","warning")
        const prod = this.listaHoja[index];
        //console.log(this.listaHoja[index])
        CARRITO.setCarrito(prod);

    },
    formatNumerPrecio(num){
        return parseFloat(num + "").toFixed(2)
    },
    getPreparePagination(){
        this.cntHojas = Math.ceil(this.cantidadProd / this.cntItemPorHoja);
        this.getDataProdListaPag();
    },
    setNumHoja(num){
        this.hojaActual = num;
        //this.viewDataHojaSc();
        this.paginadorListaServer();
        /*if (this.hojaActual==1){
            this.lasrId=0;
        }else{
            this.lasrId = this.listaHoja[this.listaHoja.length-1].prod_id
        }

        this.getDataProdListaPag();*/
    },
    setSwithHoja(num){
        console.log(num);

        if (this.hojaActual + num > 0 && this.hojaActual + num <= this.cntHojas) {
            this.hojaActual += num;
            /*if (this.hojaActual==1){
                this.lasrId=0;
            }else{
                this.lasrId = this.listaHoja[this.listaHoja.length-1].prod_id
            }*/
            this.viewDataHojaSc();

            //this.getDataProdListaPag();
        }

    },
    getDataProdListaPag(){
        const cnt = this.cntItemPorHoja;
        const min = this.lasrId;
        $.ajax({
            type: "POST",
            url: "../ajax/ajs_productos.php",
            data: { tipo: 'pag-search', cnt, min, pal: APP_PROD._data.palabra },
            success: function (resq) {
                // console.log(resq);
                resq = JSON.parse(resq);
                APP_PROD._data.listaHoja = resq
                // console.log(resq);
                console.log(resp);
                $(".scrollup").click()
            }
        });

    },

    getDataCountProd(){
        $.ajax({
            type: "POST",
            url: "../ajax/ajs_productos.php",
            data: { tipo: 'pag-search-count', pal: APP_PROD._data.palabra },
            success: function (resp) {
                if (isJson(resp)) {
                    resp = JSON.parse(resp);
                    if (resp.res) {
                        APP_PROD._data.cantidadProd = parseInt(resp.cnt);
                        APP_PROD.getPreparePagination();
                    } else {

                    }
                } else {

                }
                console.log(resp)
            }
        });

    }
        },
    computed: {
        getPagNum(){
            var numero = [];
            for (var i = 1; i <= this.cntHojas; i++) {
                numero.push(i);
            }
            console.log(numero)
            return numero;
        }
    }
    });

    var en_stock_filtro = false
    $(document).ready(function () {
        $("#en-stock").change(function () {
            en_stock_filtro = this.checked;
            APP_PROD.resetFiter();
        });
        APP_PROD.establecerTC();
        APP_PROD._data.palabra = $("#palabra").val();
        APP_PROD.paginadorListaServer()
        //APP_PROD.getDataProdListaPag2()
        APP_PROD.cargarCategorias()
        APP_PROD.cargarMarcas()
        $("#price_first").slider({
            range: true,
            min: 0,
            max: 5000,
            values: [0, 5000],
            slide: function(event, ui) {
                APP_PROD._data.valueUSDMin = ui.values[0];
                APP_PROD._data.valueUSDMax = ui.values[1];
                $("#slider_min").text(ui.values[0]);
                $("#slider_max").text(ui.values[1]);
            },
            stop: function(event, ui) {
                APP_PROD.getFiltrar();
            }
        });

        setTimeout(function () {
            $('.main_content').on('click', ".input-check-marc", function () {
                if ($(this).is(':checked')) {
                    // Hacer algo si el checkbox ha sido seleccionado
                    APP_PROD.agregarFiltroMarca($(this).val());
                } else {
                    // Hacer algo si el checkbox ha sido deseleccionado
                    APP_PROD.eliminarFiltroMarca($(this).val());
                }
                APP_PROD.resetFiter();
            });
        }, 1500)

        //APP_PROD.getDataCountProd()

        /*setTimeout(function () {
            $('.shorting_icon').on('click',function() {
                if ($(this).hasClass('grid')) {
                    $('.shop_container').removeClass('list').addClass('grid');
                    $(this).addClass('active').siblings().removeClass('active');
                }
                else if($(this).hasClass('list')) {
                    $('.shop_container').removeClass('grid').addClass('list');
                    $(this).addClass('active').siblings().removeClass('active');
                }
                $(".shop_container").append('<div class="loading_pr"><div class="mfp-preloader"></div></div>');
                setTimeout(function(){
                    $('.loading_pr').remove();
                    $container.isotope('layout');
                }, 800);
            });
        })*/
    });
</script>

</html>